server:
  port: 8080

spring:
  application:
    name: spring-security-one-time-token-login

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}
          connectiontimeout: ${MAIL_SMTP_CONNECTIONTIMEOUT:5000}
          timeout: ${MAIL_SMTP_TIMEOUT:3000}
          writetimeout: ${MAIL_SMTP_WRITETIMEOUT:5000}

gg:
  jte:
    development-mode: true
